name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile  # Path to your Dockerfile
          push: true
          tags: |
            maxdac/elixir-codespaces:${{ github.sha }}
            maxdac/elixir-codespaces:latest

      - name: Logout from Docker Hub
        run: docker logout